import { Commodity } from './models/commodity-model.js';
import { Sequelize } from 'sequelize';
import fs from 'fs';

const countries = [
  'Afghanistan',
  'Albania',
  'Antarctica',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Azerbaijan',
  'Argentina',
  'Australia',
  'Austria',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Armenia',
  'Barbados',
  'Belgium',
  'Belgium-Luxembourg',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bosnia Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'Br. Antarctic Terr.',
  'Belize',
  'Br. Indian Ocean Terr.',
  'Solomon Isds',
  'Br. Virgin Isds',
  'Brunei Darussalam',
  'EU-27',
  'Bulgaria',
  'Myanmar',
  'Burundi',
  'Belarus',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean, nes',
  'Cabo Verde',
  'Cayman Isds',
  'Central African Rep.',
  'Sri Lanka',
  'Chad',
  'Chile',
  'China',
  'Christmas Isds',
  'Cocos Isds',
  'Colombia',
  'Comoros',
  'Mayotte',
  'Congo',
  'Dem. Rep. of the Congo',
  'Cook Isds',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechoslovakia',
  'Czech Rep.',
  'Benin',
  'Denmark',
  'Dominica',
  'Dominican Rep.',
  'Ecuador',
  'Eastern Europe, nes',
  'El Salvador',
  'Equatorial Guinea',
  'Fmr Ethiopia',
  'Ethiopia',
  'Eritrea',
  'Estonia',
  'Faeroe Isds',
  'Falkland Isds (Malvinas)',
  'South Georgia and the South Sandwich Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'Fr. South Antarctic Terr.',
  'Djibouti',
  'Gabon',
  'Georgia',
  'Gambia',
  'State of Palestine',
  'Germany',
  'Fmr Dem. Rep. of Germany',
  'Fmr Fed. Rep. of Germany',
  'Ghana',
  'Northern Africa, nes',
  'Gibraltar',
  'Kiribati',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'China, Hong Kong SAR',
  'Hungary',
  'Iceland',
  'India, excl. Sikkim',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Kazakhstan',
  'Jordan',
  'Kenya',
  'Rep. of Korea',
  'Kuwait',
  'Kyrgyzstan',
  'Lebanon',
  'Lesotho',
  'Latvia',
  'Liberia',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'China, Macao SAR',
  'Madagascar',
  'Malawi',
  'Sarawak',
  'Malaysia',
  'Peninsula Malaysia',
  'Sabah',
  'Maldives',
  'Mali',
  'Malta',
  'CACM, nes',
  'Africa CAMEU region, nes',
  'LAIA, nes',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Other Asia, nes',
  'Europe EU, nes',
  'Mongolia',
  'Rep. of Moldova',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Oman',
  'Namibia',
  'Nauru',
  'Nepal',
  'Oceania, nes',
  'Netherlands',
  'Neth. Antilles',
  'Neth. Antilles and Aruba',
  'Aruba',
  'Saint Maarten',
  'Bonaire',
  'New Caledonia',
  'Vanuatu',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Other Europe, nes',
  'Niue',
  'Norfolk Isds',
  'Norway',
  'N. Mariana Isds',
  'United States Minor Outlying Islands',
  'Fmr Pacific Isds',
  'FS Micronesia',
  'Marshall Isds',
  'Palau',
  'Pakistan',
  'East and West Pakistan',
  'Fmr Panama, excl.Canal Zone',
  'Panama',
  'Fmr Panama-Canal-Zone',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Guinea-Bissau',
  'Timor-Leste',
  'Qatar',
  'Rest of America, nes',
  'North America and Central America, nes',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Ryukyu Isd',
  'Saint Helena',
  'Saint Kitts, Nevis and Anguilla',
  'Saint Kitts and Nevis',
  'Anguilla',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Europe EFTA, nes',
  'Sikkim',
  'India',
  'Singapore',
  'Slovakia',
  'Viet Nam',
  'Slovenia',
  'Somalia',
  'South Africa',
  'So. African Customs Union',
  'Zimbabwe',
  'Fmr Rhodesia Nyas',
  'Fmr Dem. Yemen',
  'Spain',
  'South Sudan',
  'Sudan',
  'Western Sahara',
  'Fmr Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'United Arab Emirates',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Isds',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'TFYR of Macedonia',
  'Fmr USSR',
  'Egypt',
  'United Kingdom',
  'United Rep. of Tanzania',
  'Fmr Tanganyika',
  'Fmr Zanzibar and Pemba Isd',
  'Bunkers',
  'Free Zones',
  'Special Categories',
  'USA',
  'US Misc. Pacific Isds',
  'US Virgin Isds',
  'Burkina Faso',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Fmr Dem. Rep. of Vietnam',
  'Fmr Rep. of Vietnam',
  'Wallis and Futuna Isds',
  'Western Asia, nes',
  'Samoa',
  'Fmr Arab Rep. of Yemen',
  'Yemen',
  'Fmr Yugoslavia',
  'Serbia and Montenegro',
  'Zambia',
];
export const commodities = [
  // { name: 'bananas', code: '0803', description: 'bananas exported (kg)' },
  // {
  //   name: 'petroleumLube',
  //   code: '2701',
  //   description: 'petroleum lube exported (kg)',
  // },
  // {
  //   name: 'pigAndPoultryFat',
  //   code: '0209',
  //   description: 'pig and poultry fat (kg)',
  // },
  // { name: 'whiskey', code: '220830', description: 'whiskey exported (liters)' },
  // {
  //   name: 'bloodAndToxinsAndCultures',
  //   code: '3002',
  //   description: 'blood, antisera, toxins, and cultures exported (kg)',
  // },
  // {
  //   name: 'fertilizers',
  //   code: '31',
  //   description: 'fertilizers exported (US$)',
  // },
  // {
  //   name: 'pharmaceuticals',
  //   code: '30',
  //   description: 'pharmaceuticals exported (US$)',
  // },
  { name: 'potatoes', code: '0701', description: 'potatoes exported (kg)' },
  // { name: 'coffee', code: '0901', description: 'coffee exported (kg)' },
  // { name: 'oats', code: '1004', description: 'oats exported (kg)' },
  // { name: 'rapeSeed', code: '1205', description: 'oats exported (kg)' },
  // { name: 'sausages', code: '1601', description: 'sausages exported (kg)' },
];

const availability = {
  bananas: [],
  petroleumLube: [],
  pigAndPoultryFat: [],
  whiskey: [],
  bloodAndToxinsAndCultures: [],
  fertilizers: [],
  pharmaceuticals: [],
  potatoes: [],
  coffee: [],
  oats: [],
  rapeSeed: [],
  sausages: [],
};
async function availableCountries() {
  try {
    for (let commodity of commodities) {
      let commodityName = commodity.name;
      for (let country of countries) {
        const data = await Commodity.findAll({
          where: {
            commodity: commodity.name,
            country: country,
          },
        });
        if (data && data.length > 3) {
          availability[commodityName].push(country);
        }
      }
      console.log(availability, ' done with ', commodityName);
    }
    console.log(availability, 'done');
    let json = JSON.stringify(availability);
    fs.writeFileSync('availability.json', json, { encoding: 'utf8' });
  } catch (err) {
    console.log(err);
  }
}

availableCountries();
