export const countryCodes:any = {
  "Afghanistan" : "AF",
  "Albania" : "AL",
  "Algeria" : "DZ",
  "American Samoa" : "AS",
  "Andorra" : "AD",
  "Angola" : "AO",
  "Antigua and Barbuda" : "AG",
  "Argentina" : "AR",
  "Armenia" : "AM",
  "Aruba" : "AW",
  "Australia" : "AU",
  "Austria" : "AT",
  "Azerbaijan" : "AZ",
  "Bahamas, The" : "BS",
  "Bahrain" : "BH",
  "Bangladesh" : "BD",
  "Barbados" : "BB",
  "Belarus" : "BY",
  "Belgium" : "BE",
  "Belize" : "BZ",
  "Benin" : "BJ",
  "Bermuda" : "BM",
  "Bhutan" : "BT",
  "Bolivia" : "BO",
  "Bosnia and Herzegovina" : "BA",
  "Botswana" : "BW",
  "Brazil" : "BR",
  "British Virgin Islands" : "VG",
  "Brunei Darussalam" : "BN",
  "Bulgaria" : "BG",
  "Burkina Faso" : "BF",
  "Burundi" : "BI",
  "Cabo Verde" : "CV",
  "Cambodia" : "KH",
  "Cameroon" : "CM",
  "Canada" : "CA",
  "Cayman Islands" : "KY",
  "Central African Republic" : "CF",
  "Chad" : "TD",
  "Channel Islands" : "JG",
  "Chile" : "CL",
  "China" : "CN",
  "Colombia" : "CO",
  "Comoros" : "KM",
  "Congo, Dem. Rep." : "CD",
  "Congo, Rep." : "CG",
  "Costa Rica" : "CR",
  "Cote d'Ivoire" : "CI",
  "Croatia" : "HR",
  "Cuba" : "CU",
  "Curacao" : "CW",
  "Cyprus" : "CY",
  "Czechia" : "CZ",
  "Denmark" : "DK",
  "Djibouti" : "DJ",
  "Dominica" : "DM",
  "Dominican Republic" : "DO",
  "Ecuador" : "EC",
  "Egypt, Arab Rep." : "EG",
  "El Salvador" : "SV",
  "Equatorial Guinea" : "GQ",
  "Eritrea" : "ER",
  "Estonia" : "EE",
  "Eswatini" : "SZ",
  "Ethiopia" : "ET",
  "Faroe Islands" : "FO",
  "Fiji" : "FJ",
  "Finland" : "FI",
  "France" : "FR",
  "French Polynesia" : "PF",
  "Gabon" : "GA",
  "Gambia, The" : "GM",
  "Georgia" : "GE",
  "Germany" : "DE",
  "Ghana" : "GH",
  "Gibraltar" : "GI",
  "Greece" : "GR",
  "Greenland" : "GL",
  "Grenada" : "GD",
  "Guam" : "GU",
  "Guatemala" : "GT",
  "Guinea" : "GN",
  "Guinea-Bissau" : "GW",
  "Guyana" : "GY",
  "Haiti" : "HT",
  "Honduras" : "HN",
  "Hong Kong SAR, China" : "HK",
  "Hungary" : "HU",
  "Iceland" : "IS",
  "India" : "IN",
  "Indonesia" : "ID",
  "Iran, Islamic Rep." : "IR",
  "Iraq" : "IQ",
  "Ireland" : "IE",
  "Isle of Man" : "IM",
  "Israel" : "IL",
  "Italy" : "IT",
  "Jamaica" : "JM",
  "Japan" : "JP",
  "Jordan" : "JO",
  "Kazakhstan" : "KZ",
  "Kenya" : "KE",
  "Kiribati" : "KI",
  "Korea, Dem. People's Rep." : "KP",
  "Korea, Rep." : "KR",
  "Kosovo" : "XK",
  "Kuwait" : "KW",
  "Kyrgyz Republic" : "KG",
  "Lao PDR" : "LA",
  "Latvia" : "LV",
  "Lebanon" : "LB",
  "Lesotho" : "LS",
  "Liberia" : "LR",
  "Libya" : "LY",
  "Liechtenstein" : "LI",
  "Lithuania" : "LT",
  "Luxembourg" : "LU",
  "Macao SAR, China" : "MO",
  "Madagascar" : "MG",
  "Malawi" : "MW",
  "Malaysia" : "MY",
  "Maldives" : "MV",
  "Mali" : "ML",
  "Malta" : "MT",
  "Marshall Islands" : "MH",
  "Mauritania" : "MR",
  "Mauritius" : "MU",
  "Mexico" : "MX",
  "Micronesia, Fed. Sts." : "FM",
  "Moldova" : "MD",
  "Monaco" : "MC",
  "Mongolia" : "MN",
  "Montenegro" : "ME",
  "Morocco" : "MA",
  "Mozambique" : "MZ",
  "Myanmar" : "MM",
  "Namibia" : "NA",
  "Nauru" : "NR",
  "Nepal" : "NP",
  "Netherlands" : "NL",
  "New Caledonia" : "NC",
  "New Zealand" : "NZ",
  "Nicaragua" : "NI",
  "Niger" : "NE",
  "Nigeria" : "NG",
  "North Macedonia" : "MK",
  "Northern Mariana Islands" : "MP",
  "Norway" : "NO",
  "Oman" : "OM",
  "Pakistan" : "PK",
  "Palau" : "PW",
  "Panama" : "PA",
  "Papua New Guinea" : "PG",
  "Paraguay" : "PY",
  "Peru" : "PE",
  "Philippines" : "PH",
  "Poland" : "PL",
  "Portugal" : "PT",
  "Puerto Rico" : "PR",
  "Qatar" : "QA",
  "Romania" : "RO",
  "Russian Federation" : "RU",
  "Rwanda" : "RW",
  "Samoa" : "WS",
  "San Marino" : "SM",
  "Sao Tome and Principe" : "ST",
  "Saudi Arabia" : "SA",
  "Senegal" : "SN",
  "Serbia" : "RS",
  "Seychelles" : "SC",
  "Sierra Leone" : "SL",
  "Singapore" : "SG",
  "Sint Maarten (Dutch part)" : "SX",
  "Slovak Republic" : "SK",
  "Slovenia" : "SI",
  "Solomon Islands" : "SB",
  "Somalia" : "SO",
  "South Africa" : "ZA",
  "South Sudan" : "SS",
  "Spain" : "ES",
  "Sri Lanka" : "LK",
  "St. Kitts and Nevis" : "KN",
  "St. Lucia" : "LC",
  "St. Martin (French part)" : "MF",
  "St. Vincent and the Grenadines" : "VC",
  "Sudan" : "SD",
  "Suriname" : "SR",
  "Sweden" : "SE",
  "Switzerland" : "CH",
  "Syrian Arab Republic" : "SY",
  "Tajikistan" : "TJ",
  "Tanzania" : "TZ",
  "Thailand" : "TH",
  "Timor-Leste" : "TL",
  "Togo" : "TG",
  "Tonga" : "TO",
  "Trinidad and Tobago" : "TT",
  "Tunisia" : "TN",
  "Turkiye" : "TR",
  "Turkmenistan" : "TM",
  "Turks and Caicos Islands" : "TC",
  "Tuvalu" : "TV",
  "Uganda" : "UG",
  "Ukraine" : "UA",
  "United Arab Emirates" : "AE",
  "United Kingdom" : "GB",
  "United States" : "US",
  "Uruguay" : "UY",
  "Uzbekistan" : "UZ",
  "Vanuatu" : "VU",
  "Venezuela, RB" : "VE",
  "Vietnam" : "VN",
  "Virgin Islands (U.S.)" : "VI",
  "West Bank and Gaza" : "PS",
  "Yemen, Rep." : "YE",
  "Zambia" : "ZM",
  "Zimbabwe" : "ZW",
  "World" : "WLD",
  "Arab World" : "1A",
  "Caribbean small states" : "S3",
  "Central Europe and the Baltics" : "B8",
  "East Asia & Pacific" : "Z4",
  "East Asia & Pacific (excluding high income)" : "4E",
  "Euro area" : "XC",
  "Europe & Central Asia" : "Z7",
  "Europe & Central Asia (excluding high income)" : "7E",
  "European Union" : "EU",
  "Fragile and conflict affected situations" : "F1",
  "Heavily indebted poor countries (HIPC)" : "XE",
  "Latin America & Caribbean" : "ZJ",
  "Latin America & Caribbean (excluding high income)" : "XJ",
  "Least developed countries: UN classification" : "XL",
  "Middle East & North Africa" : "ZQ",
  "Middle East & North Africa (excluding high income)" : "XQ",
  "North America" : "XU",
  "OECD members" : "OE",
  "Other small states" : "S4",
  "Pacific island small states" : "S2",
  "Small states" : "S1",
  "South Asia" : "8S",
  "Sub-Saharan Africa" : "ZG",
  "Sub-Saharan Africa (excluding high income)" : "ZF",
  "High income" : "XD",
  "Low & middle income" : "XO",
  "Low income" : "XM",
  "Lower middle income" : "XN",
  "Middle income" : "XP",
  "Upper middle income" : "XT",
}