export const queries = {
  // CATEGORY
  Demographics: {
    BirthRate: {
      description: 'Birth rate, crude (per 1,000 people)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.DYN.CBRT.IN?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.DYN.CBRT.IN',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 1,000 people',
      provider: 'World Bank',
    },
    DeathRate: {
      description: 'Death rate, crude (per 1,000 people)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.DYN.CDRT.IN?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.DYN.CDRT.IN',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 1,000 people',
      provider: 'World Bank',
    },
    MaleLifeExpectancy: {
      description: 'Life expectancy at birth, total (years)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.DYN.LE00.MA.IN?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.DYN.LE00.MA.IN',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'years',
      provider: 'World Bank',
    },
    FemaleLifeExpectancy: {
      description: 'Life expectancy at birth, total (years)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.DYN.LE00.FE.IN?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.DYN.LE00.FE.IN',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'years',
      provider: 'World Bank',
    },
    Population: {
      description: 'Population, total',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.POP.TOTL?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.POP.TOTL',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'total',
      provider: 'World Bank',
    },
  },
  Agriculture: {
    AgriculturalLand: {
      description: 'Agricultural land (% of land area)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/AG.LND.AGRI.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'AG.LND.AGRI.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    ForestArea: {
      description: 'Forest area (% of land area)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/AG.LND.FRST.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'AG.LND.FRST.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    FertilizerConsumption: {
      description:
        'Fertilizer consumption (kilograms per hectare of arable land)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/AG.CON.FERT.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'AG.CON.FERT.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kilograms per hectare of arable land',
      provider: 'World Bank',
    },
    IrrigatedLand: {
      description: 'Irrigated land (% of total agricultural land)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/AG.LND.IRIG.AG.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'AG.LND.IRIG.AG.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
  },
  Bananas: {
    BananaWorldExports: {},
  },
  Economy: {
    GDP: {
      description: 'GDP (current US$)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/NY.GDP.MKTP.CD?date=startYear:endYear&format=json`,
      indicatorCode: 'NY.GDP.MKTP.CD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'current US$',
      provider: 'World Bank',
    },
    ExportGoods: {
      description: 'Exports of goods and services (% of GDP)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/NE.EXP.GNFS.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'NE.EXP.GNFS.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    GrossSaving: {
      description: 'Gross savings (% of GDP)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/NY.GNS.ICTR.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'NY.GNS.ICTR.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    ConsumerPriceIndex: {
      description: 'Consumer price index (2010 = 100)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FP.CPI.TOTL?date=startYear:endYear&format=json`,
      indicatorCode: 'FP.CPI.TOTL',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '2010 = 100',
      provider: 'World Bank',
    },
  },
  Education: {
    SchoolEnrollment: {
      description:
        'School enrollment, primary and secondary (gross), gender parity index (GPI)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SE.ENR.PRSC.FM.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SE.ENR.PRSC.FM.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'GPI',
      provider: 'World Bank',
    },
    SecondarySchoolProgression: {
      description: 'Progression to secondary school (%)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SE.SEC.PROG.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SE.SEC.PROG.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    PrimarySchoolCompletion: {
      description: 'Primary completion rate, total (% of relevant age group)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SE.PRM.CMPT.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SE.PRM.CMPT.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    SecondarySchoolCompletion: {
      description: 'Secondary completion rate, total (% of relevant age group)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SE.SEC.CMPT.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SE.SEC.CMPT.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
  },
  Energy: {
    ElectricityConsumption: {
      description: 'Electricity consumption (kWh per capita)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EG.USE.ELEC.KH.PC?date=startYear:endYear&format=json`,
      indicatorCode: 'EG.USE.ELEC.KH.PC',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kWh per capita',
      provider: 'World Bank',
    },
    ElectricityProduction: {
      description: 'Electricity production (kWh per capita)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EG.USE.ELEC.KH.PC?date=startYear:endYear&format=json`,
      indicatorCode: 'EG.USE.ELEC.KH.PC',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kWh per capita',
      provider: 'World Bank',
    },
    ElectricityProductionRenewable: {
      description:
        'Electricity production from renewable sources, excluding hydroelectric (kWh)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EG.FEC.RNEW.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'EG.FEC.RNEW.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kWh',
      provider: 'World Bank',
    },
    ElectricityProductionHydroelectric: {
      description: 'Electricity production from hydroelectric sources (kWh)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EG.ELC.HYRO.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'EG.ELC.HYRO.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kWh',
      provider: 'World Bank',
    },
  },
  Environment: {
    CO2Emissions: {
      description: 'CO2 emissions (metric tons per capita)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EN.ATM.CO2E.PC?date=startYear:endYear&format=json`,
      indicatorCode: 'EN.ATM.CO2E.PC',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'metric tons per capita',
      provider: 'World Bank',
    },
    CO2EmissionsTotal: {
      description: 'CO2 emissions (kt)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EN.ATM.CO2E.KT?date=startYear:endYear&format=json`,
      indicatorCode: 'EN.ATM.CO2E.KT',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'kt',
      provider: 'World Bank',
    },
    CO2EmissionsTotalGDPGrowth: {
      description: 'CO2 emissions growth (annual %)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/EN.ATM.CO2E.GF.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'EN.ATM.CO2E.GF.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'annual %',
      provider: 'World Bank',
    },
    AveragePrecipitation: {
      description: 'Average precipitation in depth (mm per year)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/AG.LND.PRCP.MM?date=startYear:endYear&format=json`,
      indicatorCode: 'AG.LND.PRCP.MM',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'mm per year',
      provider: 'World Bank',
    },
  },
  Entertainment: {
    CinemaAdmissions: {
      description: 'Cinema admissions (number)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/CM.MKT.LCAP.CD?date=startYear:endYear&format=json`,
      indicatorCode: 'CM.MKT.LCAP.CD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'number',
      provider: 'World Bank',
    },
    InternetUsers: {
      description: 'Internet users (per 100 people)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/IT.NET.USER.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'IT.NET.USER.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100 people',
      provider: 'World Bank',
    },
    MobileCellularSubscriptions: {
      description: 'Mobile cellular subscriptions (per 100 people)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/IT.CEL.SETS.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'IT.CEL.SETS.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100 people',
      provider: 'World Bank',
    },
    Television: {
      description: 'Television, fixed lines (per 100 people)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/IT.MLT.MAIN.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'IT.MLT.MAIN.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100 people',
      provider: 'World Bank',
    },
  },
  Finance: {
    BankAssets: {
      description: 'Bank assets (current US$)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FI.RES.TOTL.CD?date=startYear:endYear&format=json`,
      indicatorCode: 'FI.RES.TOTL.CD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'current US$',
      provider: 'World Bank',
    },
    BankDeposits: {
      description: 'Bank deposits (current US$)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FI.AST.TOTL.CD?date=startYear:endYear&format=json`,
      indicatorCode: 'FI.AST.TOTL.CD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'current US$',
      provider: 'World Bank',
    },
    BankLending: {
      description: 'Bank lending interest rate (%)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FR.INR.LEND?date=startYear:endYear&format=json`,
      indicatorCode: 'FR.INR.LEND',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
    BankLoans: {
      description: 'Bank loans and advances (current US$)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FI.LBL.TOTL.CD?date=startYear:endYear&format=json`,
      indicatorCode: 'FI.LBL.TOTL.CD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'current US$',
      provider: 'World Bank',
    },
    BankProfitMargin: {
      description: 'Bank profit margin on lending (%)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/FR.INR.LEND?date=startYear:endYear&format=json`,
      indicatorCode: 'FR.INR.LEND',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: '%',
      provider: 'World Bank',
    },
  },
  Health: {
    AdultMortalityRate: {
      description:
        'Adult mortality rate (probability of dying between 15 and 60 years per 1000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SP.DYN.AMRT.MA?date=startYear:endYear&format=json`,
      indicatorCode: 'SP.DYN.AMRT.MA',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'x 1000 population',
      provider: 'World Bank',
    },
    MortalityByRoadTraffic: {
      description:
        'Mortality rate attributed to road traffic injury (per 100,000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SH.STA.TRAF.P5?date=startYear:endYear&format=json`,
      indicatorCode: 'SH.STA.TRAF.P5',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100,000 population',
      provider: 'World Bank',
    },
    MortalityByTuberculosis: {
      description:
        'Mortality rate attributed to tuberculosis (per 100,000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SH.TBS.INCD?date=startYear:endYear&format=json`,
      indicatorCode: 'SH.TBS.INCD',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100,000 population',
      provider: 'World Bank',
    },
    MortalityByHIV: {
      description:
        'Mortality rate attributed to HIV/AIDS (per 100,000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SH.DYN.AIDS.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SH.DYN.AIDS.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100,000 population',
      provider: 'World Bank',
    },
    MortalityByDiarrhea: {
      description:
        'Mortality rate attributed to diarrheal diseases (per 100,000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SH.DTH.COMM.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SH.DTH.COMM.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100,000 population',
      provider: 'World Bank',
    },
    MortalityByCancer: {
      description:
        'Mortality rate attributed to cancer (per 100,000 population)',
      queryString: `http://api.worldbank.org/v2/country/countryCode/indicator/SH.DTH.CANC.ZS?date=startYear:endYear&format=json`,
      indicatorCode: 'SH.DTH.CANC.ZS',
      parameters_needed: ['countryCode', 'startYear', 'endYear'],
      unit: 'per 100,000 population',
      provider: 'World Bank',
    },
  },
  History: {},
  Science: {},
  Space: {},
  Transportation: {},
  Weather: {
    AverageTemperature: {
      description: 'Average Daily Temperature (Celsius)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'temperature_2m_mean',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'Celsius',
      provider: 'Open-Meteo',
    },
    AverageHighTemperature: {
      description: 'Average Daily High Temperature (Celsius)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'temperature_2m_max',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'Celsius',
      provider: 'Open-Meteo',
    },
    AverageLowTemperature: {
      description: 'Average Daily Low Temperature (Celsius)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'temperature_2m_min',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'Celsius',
      provider: 'Open-Meteo',
    },
    RainFall: {
      description: 'Daily Rain (mm)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'precipitation_amount',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'mm',
      provider: 'Open-Meteo',
    },
    SnowFall: {
      description: 'Daily Snow (mm)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'snowfall_amount',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'mm',
      provider: 'Open-Meteo',
    },
    WindSpeed: {
      description: 'Average Maximum Wind Speed (km/h)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'wind_speed_10m_max',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'km/h',
      provider: 'Open-Meteo',
    },
    AverageHumidity: {
      description: 'Average Daily Humidity (%)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'relative_humidity_2m_mean',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: '%',
      provider: 'Open-Meteo',
    },
    AverageWindSpeed: {
      description: 'Average Daily Wind Speed (m/s)',
      queryString: `https://archive-api.open-meteo.com/v1/archive?latitude=lat&longitude=lng&start_date=startYear-01-01&end_date=endYear-12-31&daily=indicatorCode&timezone=America%2FAnchorage`,
      indicatorCode: 'wind_speed_10m_mean',
      parameters_needed: ['city', 'startYear', 'endYear'],
      unit: 'm/s',
      provider: 'Open-Meteo',
    },
  },
};
